version: '2'
services:
  nginx:
    build: https://github.com/ThomasMatysiak/DockerStart
    ports:
      - 80:80
      - 443:443
    links:
      - php
  php:
    build: https://github.com/ThomasMatysiak/DockerPHP
    links:
      - postgresql
  postgresql:
    build: https://github.com/ThomasMatysiak/DockerPostgre
